blank_issues_enabled: false
contact_links:
  - name: 🆘 Need Help?
    url: https://github.com/Davy917/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and get help from the community
  - name: 💬 General Discussion
    url: https://github.com/Davy917/skills-expand-your-team-with-copilot/discussions
    about: Discuss ideas and share feedback about the school activities system